language: objective-c
os: osx
osx_image: xcode10.2
before_install:
  - gem install xcpretty
  - brew update
  - brew upgrade carthage
  - carthage update --no-use-binaries --platform ios $@
before_script:
  - set -o pipefail
script:
  - xcodebuild test -project ./RxDucks.xcodeproj -scheme RxDucksTests -configuration Debug -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=12.2,name=iPhone 8' | xcpretty -c
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
